name: Build on branch

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        branch: [v1.0.0-rc2]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash -lc "pacman -S --needed mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-nasm mingw-w64-x86_64-yasm mingw-w64-x86_64-ninja mingw-w64-x86_64-pkg-config mingw-w64-x86_64-meson git base-devel autotools --noconfirm"
    - name: build
      shell: cmd
      run: |
        set MSYSTEM=MINGW64
        set HOME=${{ github.workspace }}
        set CFLAGS=-flto -v
        set CXXFLAGS=%CFLAGS%
        set LDFLAGS=-static -static-libgcc -static-libstdc++ -flto -s
        git clone --depth 1 -b ${{ matrix.branch }} https://gitlab.com/AOMediaCodec/SVT-AV1.git
        C:\msys64\usr\bin\bash -lc "cd SVT-AV1 && mkdir binary && cd binary && cmake .. -G 'Ninja' -D BUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release"
        C:\msys64\usr\bin\bash -lc "cd SVT-AV1/binary && ninja"
        copy /y SVT-AV1\Bin\Release\SvtAv1EncApp.exe SvtAv1EncApp.exe
        copy /y SVT-AV1\LICENSE.md LICENSE.md
        copy /y SVT-AV1\PATENTS.md PATENTS.md
        7z a "SVT-AV1_${{ matrix.branch }}.7z" SvtAv1EncApp.exe LICENSE.md PATENTS.md
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: SVT-AV1
        path: |
          SVT-AV1_*.7z

  create_release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - uses: actions/download-artifact@v2
      with:
        name: SVT-AV1
        path: artifacts
    
    - name: Get Date
      id: get_date
      run: |
        DATE_TIME=`date +'%Y-%m-%d-%H-%M-%S'`
        echo "::set-output name=DATE_TIME::${DATE_TIME}"        
    # https://github.com/Mr-Ojii/L-SMASH-Works-Auto-Builds
    - name: Create a Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_NAME=Build-${{ steps.get_date.outputs.DATE_TIME }}
        TAG_NAME=build-${{ steps.get_date.outputs.DATE_TIME }}
        assets=()
        for asset in ${{ github.workspace }}/artifacts/*.7z; do
          assets+=("-a" "$asset")
        done
        hub release create "${assets[@]}" -m "$RELEASE_NAME" "$TAG_NAME"
