name: Build on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [v0.8.7, v0.8.6, 0.8.8-rc1, 0.8.8-rc2]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash -lc "pacman -S mingw-w64-x86_64-cmake mingw-w64-x86_64-nasm mingw-w64-x86_64-yasm mingw-w64-x86_64-meson mingw-w64-x86_64-ninja --noconfirm"
    - name: configure
      shell: cmd
      run: |
        set MSYSTEM=MINGW64
        set HOME=${{ github.workspace }}
        git clone -b ${{ matrix.version }} https://gitlab.com/AOMediaCodec/SVT-AV1.git
        C:\msys64\usr\bin\bash -lc "cd SVT-AV1 && mkdir binary && cd binary && cmake .. -G 'Ninja' -D BUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS='-flto' -DCMAKE_CXX_FLAGS='-flto' -DCMAKE_EXE_LINKER_FLAGS='-static -static-libgcc -flto -s' -DCMAKE_BUILD_TYPE=Release"
    - name: make
      shell: cmd
      run: |
        set MSYSTEM=MINGW64
        set HOME=${{ github.workspace }}
        C:\msys64\usr\bin\bash -lc "cd SVT-AV1/binary && ninja"
        copy /y SVT-AV1\Bin/Release\SvtAv1EncApp.exe SvtAv1EncApp.exe
        copy /y SVT-AV1\LICENSE.md LICENSE.md
        copy /y SVT-AV1\PATENTS.md PATENTS.md
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: SVT-AV1_${{ matrix.version }}
        path: |
          SvtAv1EncApp.exe
          LICENSE.md
          PATENTS.md
